name: HubHaven
version: '1.0-SNAPSHOT'
main: com.github._1mag1n33dev.HubHaven.HubHaven
api-version: '1.8'
load: POSTWORLD
authors: [ 1mag1n33dev ]
commands:
  hub:
    description: Makes you go back to the hub
    usage: /hub
  hubhaven:
    description: Main command for HubHaven
    usage: /hubhaven <subcommand>
    aliases: [hh]

permissions:
  hubhaven.use:
    description: Allows regular players to use HubHaven commands
    default: true
  hubhaven.admin:
    description: Allows admins to use admin HubHaven commands
    default: op
  hubhaven.developer:
    description: Allows admins to debug certain things in the plugin
    default: op